### ISSUE TITLE
[question]  MVE library symbols

### ISSUE THREAD

**Issue by nukeykt** [klei1984/max#29]
hi,
Just wanted to ask how did you obtain symbols for the mve library? Basically I want to reverse-engineer mve library from other dos game: redneck rampage rides again. Thanks

**Comment by nukeykt** [comment]
thanks,

my goal is to make matching decompilation of redneck rampage games, so plan is to completely reconstruct MVE library (excluding SOS for now) so it compiles with watcom and tasm(?) 😄

Yea, I found symbols in fallout games but obviosly they don't cover DOS/VESA/SOS related functions. mapper2.exe symbols also don't have symbols for C module of MVE for some reason, but has for assembly module though. I also found debug symbols in virtual pool game, but seems it is earlier version of library so, a lot of functions differ too.

I mainly ask here because I was inspecting maxrun.in file found in git history, and it have symbol names that I was not able to find in other games, so I though maybe there's other games with leaked symbols that I missed.

If it is ok for you, I think I'll just pull names from maxrun.in for now.

**Comment by klei1984** [comment]
If you target MS-DOS, then what you need is Descent II instead of Fallout's mapper2. Details below.

- Watcom C/C++ runtime libraries and the bundled Tenberry's DOS/4G(W) DPMI client API symbols are taken from original Watcom 10.5 compiler libraries and partly reconstructed from actual first public release of Open Watcom compiler's source code by hand. I wrote python scripts to detect function signatures in disassembly listings too to partly automate the work. Some of my scripts can be found in my le_disasm repository I think.
- SOS 3.x/MVE 32 bit (old)/VBE 1.x (VESA) library symbols are available in many setup.exe and install.exe programs found in Interplay and Parallax games. They mostly compiled these in debug mode.
- The Descent II setup.exe program embeds the MS-DOS 32 bit MVE library, the VBE 1.1 or was it 1.2 library, and SOS 3.x library. If you did not find some of the symbols you need in mapper2.exe (Windows 32 bit PE architecture), then you will find all of those in that setup.exe. Its again Watcom DWARF format.
- The maxrun.in file symbols are auto generated by le_disasm that receives a post processed map file from my IDA database for MAX. I also made some python scripts that was able to synchronize symbols in IDA and maxrun.in.

And if you really want to rebuild for MS-DOS, then I highly recommend to set up an actual MS-DOS system, e.g. under VirtualBox, and install the exact same original Watcom compiler infrastructure that Redneck Rampage used. It is easy to identify the matching compiler version via the compiler libraries' disassembly listings that you can create using wdis or wdump from OpenWatcom. Just compare those listings to the matching functions in RA.EXE. Your best bets are v9.5b, v10.0a, v10.5 or v11.0c. For MAX development I made an MS-DOS setup with cd-rom, mouse, sound blaster drivers, all watcom compilers, norton commander and some borland stuff too but I forgot actually why...

If you use IDA Freeware as a database tool, make sure to unbind the DOS extender from RA.EXE using PMODE/W tools and analyze the unbound linear executable only otherwise you will have a lot of trouble. Le_disasm only works with unbound linear executables. You will have to set up all segments manually by hand, but you can obtain all relevant information from le_disasm or from wdump or wdis.

In the original source code distribution of Descent I, or Descent II with DOS and Windows targets, you will find useful makefile examples to build actual DOS/4GW 386 linear executables that are bound to a DOS extender.

In RR.EXE you will find many symbols for game specific functions. GF1 library functions you can also find in setup.exe and install.exe programs from Interplay. I am sure RR and RA executables share a lot of similarities.

You can find the actual SOS 3.x Watcom libraries in the Witchaven 1 & 2 source distributions on GitHub with makefiles so you could link those directly and you do not have to skip audio or reimplement those aspects at all.

Note that le_disasm (maxrun.in) is generating GNU GCC AT&T assembly format while you would need Watcom flavor.

One last thing to note is that DOS/4G(W) 1.97 is defective. Tenberry released DOS/4G 2.01 later on which fixes several memory management issues and adds some new features too I think. Alternatively you might consider other extenders like DOS32/A or PMODE/W...

**Comment by nukeykt** [comment]
Thanks 😃 

I checked setup.exe from shareware version of descent II while was searching, but it didn't have debug symbols. Will check other versions then 👍

DOSBox works well enough for watcom/tasm actually and its mounting directory capability is quite convenient. Windows NT version of watcom also works just fine under modern windows heh

I have original Redneck Rampage more-or-less reconstructed, only 3 functions differs, otherwise it is byte-by-byte matching:

https://github.com/nukeykt/Redneck-Rampage-RE

This also includes Rides Again, but MVE/SOS modules are completely missing at the moment.

Redneck Rampage Rides Again seemed to use SOS v4.x. leaked corridor 8 source code has very close version, but at least one module had differences (different compiler flag).

Both versions are built using watcom 10.5

**Comment by nukeykt** [comment]
checked other versions of descent 2, still didn't find one with debug symbols. but I found something called in ENGAGE.EXE that has mve sybmols inside Descent to Undermountain cd file

**Comment by klei1984** [comment]
It is in the GOG.com Descent II setup.exe.

**Comment by nukeykt** [comment]
ah, interesting, thanks 👍. I was checking CD images found on archive.org

**Comment by klei1984** [comment]
Interesting, the same Engage Net advertisement is found on the Spanish MAX retail CD-ROM, but there the executable was built in release mode. Every other files are 100% same though. Oh! The INSTALL.EXE contains Tim Cain's GNW engine with debug symbols 😄
